# Generated by Django 3.1.5 on 2021-01-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friendship1',
            table='friendship_table',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_table',
        ),
    ]
